apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-curl-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: busybox-curl
              image: busyboxplus:curl
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Running health curl"
                  curl -s http://todoapp-service.todoapp.svc.cluster.local/api/health
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
